# Smart House Configuration File

devices:
  - name: Living Room Light
    type: LIGHTING
    power: 100.0
  
  - name: Fridge
    type: APPLIANCE
    power: 300.0

energies:
  - name: Solar Panels
    type: SOLAR
    output: 1500.0
  
  - name: Grid Power
    type: GRID
    output: 4000.0

batteries:
  - name: Main Battery
    capacity: 10000.0
    maxChargeRate: 2000.0