# Smart House Configuration File

devices:
  - name: Living Room Lights
    type: LIGHTING
    power: 100.0

energies:
  - name: Solar Panels
    type: SOLAR
    output: 1000.0


batteries:
  - name: Main Battery
    capacity: 10000.0
    maxChargeRate: 800.0
    maxDischargeRate: 800.0